Repository afet-yonetim-sistemi/ays-be, pull requests merged in 2023-07, with the labels that each got.

#109 Ambiguous Mapping Error Has Been Fixed
  src/main/java/com/ays/admin_user/controller/AdminUserController.java
  src/main/java/com/ays/user/controller/UserController.java
Labels: bug, in development

#110 Admin User Controller and User Controller Tests Have Been Fixed
  src/test/java/com/ays/admin_user/controller/AdminUserControllerTest.java
  src/test/java/com/ays/user/controller/UserControllerTest.java
Labels: bug, in review

#120 Refactor filterChain of SecurityConfiguration
  src/main/java/com/ays/auth/config/SecurityConfiguration.java
Labels: in review

#117 CONTRIBUTING.md File Has Been Updated for Branch and Pull Request Naming Conventions
  CONTRIBUTING.md
Labels: documentation, refactor

#119 README.md File Has Been Updated for Pull Request Naming Conventions
  README.md
Labels: documentation, refactor

#104 #75 | Private and Public Keys Have Been Encrypted & Flows and Tests Have Been Refactored
  README.md
  pom.xml
  src/main/java/com/ays/auth/config/AysTokenConfigurationParameter.java
  src/main/java/com/ays/auth/service/impl/AysTokenServiceImpl.java
  src/main/java/com/ays/auth/util/KeyConverter.java
  src/main/resources/db/changelog/changes/1-ays-ddl.xml
  src/main/resources/db/changelog/changes/2-ays-dml.xml
  src/test/java/com/ays/AbstractRestControllerTest.java
  src/test/java/com/ays/auth/service/impl/AysTokenServiceImplTest.java
  src/test/java/com/ays/auth/util/KeyConverterTest.java
  src/test/java/com/ays/parameter/model/AysParameterBuilder.java
Labels: in review

#114 #111 | Phone Number Validations and Other Validations Have Been Fixed
  src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
  src/main/java/com/ays/admin_user/repository/AdminUserRepository.java
  src/main/java/com/ays/common/model/AysPhoneNumber.java
  src/main/java/com/ays/common/util/validation/PhoneNumberValidator.java
  src/main/java/com/ays/user/controller/UserController.java
  src/main/java/com/ays/user/model/dto/request/UserSaveRequest.java
  src/main/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequest.java
  src/main/java/com/ays/user/model/dto/request/UserUpdateRequest.java
  src/main/java/com/ays/user/model/entity/UserEntity.java
  src/main/resources/db/changelog/changes/1-ays-ddl.xml
  src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImplTest.java
  src/test/java/com/ays/common/model/AysPhoneNumberBuilder.java
  src/test/java/com/ays/user/controller/UserControllerTest.java
Labels: refactor

#121 #115 | Refactor Admin Default Role
  src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
  src/main/java/com/ays/admin_user/model/enums/AdminRole.java
  src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterRequestToAdminUserEntityMapper.java
Labels: refactor

#122 #116 | Refactor default createdUser and updatedUser values
  src/main/java/com/ays/common/model/entity/BaseEntity.java
Labels: refactor

#125 #123 | Add institution name to token for Admin User
  src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
  src/main/java/com/ays/auth/model/enums/AysTokenClaims.java
Labels: feature

#126 #124 | Building And Running Flows of Application Have Been Fixed
  .github/workflows/application-health-checker.yml
  .github/workflows/branch-reporter.yml
  .github/workflows/deploy-main.yml
  .github/workflows/live/deploy.sh
  .github/workflows/live/deployment.yml
  .github/workflows/pull-request-checker.yml
  .github/workflows/test/deploy.sh
  .github/workflows/test/deployment.yml
  .gitignore
  Dockerfile
  README.md
  build/deploy.sh
  docker-compose-live.yml
  docker-compose-test.yml
  template-settings.xml
Labels: bug

#127 Phone Number Validations Has Been Fixed
  src/main/java/com/ays/common/util/validation/PhoneNumber.java
  src/main/java/com/ays/common/util/validation/PhoneNumberValidator.java
  src/main/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequest.java
  src/main/java/com/ays/user/model/dto/request/UserUpdateRequest.java
  src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
  src/test/java/com/ays/common/util/exception/model/AysErrorBuilder.java
  src/test/java/com/ays/user/controller/UserAuthControllerTest.java
  src/test/java/com/ays/user/controller/UserControllerTest.java
  src/test/java/com/ays/util/AysMockResultMatchersBuilders.java
Labels: bug, in review

#128 Application Status Badge Has Been Added to README.md File
  README.md
Labels: feature, in review

#134 GitHub Actions Deployment Flow Has Been Fixed
  .github/workflows/application-health-checker.yml
  .github/workflows/live-environment-deployment.yml
  .github/workflows/test-environment-deployment.yml
Labels: bug

#112 #105 | Create Assignment And Location Domain
  pom.xml
  src/main/java/com/ays/assignment/model/Assignment.java
  src/main/java/com/ays/assignment/model/dto/request/AssignmentListRequest.java
  src/main/java/com/ays/assignment/model/dto/request/AssignmentSearchRequest.java
  src/main/java/com/ays/assignment/model/dto/response/AssignmentResponse.java
  src/main/java/com/ays/assignment/model/dto/response/AssignmentSearchResponse.java
  src/main/java/com/ays/assignment/model/entity/AssignmentEntity.java
  src/main/java/com/ays/assignment/model/enums/AssignmentStatus.java
  src/main/java/com/ays/assignment/model/mapper/AssignmentEntityToAssignmentMapper.java
  src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentEntityMapper.java
  src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentResponseMapper.java
  src/main/java/com/ays/assignment/repository/AssignmentEntityRepository.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentAlreadyAssignedException.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentAlreadyAvailableException.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentAlreadyDoneException.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentAlreadyInProgressException.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentAlreadyReservedException.java
  src/main/java/com/ays/assignment/util/exception/AysAssignmentNotExistByIdException.java
  src/main/java/com/ays/location/model/UserLocation.java
  src/main/java/com/ays/location/model/dto/request/UserLocationRequest.java
  src/main/java/com/ays/location/model/entity/UserLocationEntity.java
  src/main/java/com/ays/location/model/mapper/UserLocationEntityToUserLocationMapper.java
  src/main/java/com/ays/location/model/mapper/UserLocationToUserLocationEntityMapper.java
  src/main/java/com/ays/location/repository/UserLocationRepository.java
  src/main/java/com/ays/location/util/exception/AysUserLocationNotExistByIdException.java
Labels: feature
