Repository afet-yonetim-sistemi/ays-be, pull requests merged in 2023-06, with the labels that each got.

#65 Change targetPort for service.yml and containerPort for deployment.yml in Kubernetes
  deployment.yml
  service.yml
Labels: in review, refactor

#46 Implementation of showing all administrators through admin panel
  src/main/java/com/ays/admin_user/controller/AdminUserController.java
  src/main/java/com/ays/admin_user/model/AdminUser.java
  src/main/java/com/ays/admin_user/model/dto/request/AdminUserListRequest.java
  src/main/java/com/ays/admin_user/model/dto/response/AdminUsersResponse.java
  src/main/java/com/ays/admin_user/model/mapper/AdminUserEntityToAdminUserMapper.java
  src/main/java/com/ays/admin_user/model/mapper/AdminUserToAdminUsersResponseMapper.java
  src/main/java/com/ays/admin_user/repository/AdminUserRepository.java
  src/main/java/com/ays/admin_user/service/AdminUserService.java
  src/main/java/com/ays/admin_user/service/impl/AdminUserServiceImpl.java
  src/main/java/com/ays/auth/model/AysIdentity.java
  src/main/java/com/ays/auth/model/enums/AysUserType.java
  src/main/java/com/ays/common/model/AysSpecification.java
  src/main/resources/db/changelog/changes/1-ays-ddl.xml
  src/main/resources/db/changelog/changes/2-ays-dml.xml
  src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
  src/test/java/com/ays/admin_user/controller/AdminUserControllerTest.java
  src/test/java/com/ays/admin_user/model/dto/request/AdminUserListRequestBuilder.java
  src/test/java/com/ays/admin_user/model/entity/AdminUserEntityBuilder.java
  src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImplTest.java
  src/test/java/com/ays/admin_user/service/impl/AdminUserServiceImplTest.java
Labels: feature

#48 Secure Logout Flows Have Been Created for Admin Users & Users
  src/main/java/com/ays/admin_user/controller/AdminUserAuthController.java
  src/main/java/com/ays/admin_user/service/AdminUserAuthService.java
  src/main/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImpl.java
  src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImpl.java
  src/main/java/com/ays/auth/filter/AysBearerTokenAuthenticationFilter.java
  src/main/java/com/ays/auth/model/AysIdentity.java
  src/main/java/com/ays/auth/model/dto/request/AysTokenInvalidateRequest.java
  src/main/java/com/ays/auth/model/entity/AysInvalidTokenEntity.java
  src/main/java/com/ays/auth/repository/AysInvalidTokenRepository.java
  src/main/java/com/ays/auth/service/AysInvalidTokenService.java
  src/main/java/com/ays/auth/service/impl/AysInvalidTokenServiceImpl.java
  src/main/java/com/ays/auth/service/impl/AysTokenServiceImpl.java
  src/main/java/com/ays/auth/util/exception/TokenAlreadyInvalidatedException.java
  src/main/java/com/ays/user/controller/UserAuthController.java
  src/main/java/com/ays/user/model/entity/UserEntity.java
  src/main/java/com/ays/user/service/UserAuthService.java
  src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserServiceImpl.java
  src/main/resources/db/changelog/changes/3-ays-ddl.xml
  src/test/java/com/ays/AbstractUnitTest.java
  src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
  src/test/java/com/ays/admin_user/controller/AdminUserControllerTest.java
  src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
  src/test/java/com/ays/auth/model/AysTokenBuilder.java
  src/test/java/com/ays/auth/model/dto/request/AysTokenInvalidateRequestBuilder.java
  src/test/java/com/ays/auth/model/entity/AysInvalidTokenEntityBuilder.java
  src/test/java/com/ays/auth/service/impl/AysInvalidTokenServiceImplTest.java
  src/test/java/com/ays/auth/service/impl/AysTokenServiceImplTest.java
  src/test/java/com/ays/common/util/exception/model/AysErrorBuilder.java
  src/test/java/com/ays/user/controller/UserAuthControllerTest.java
  src/test/java/com/ays/user/controller/UserControllerTest.java
  src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java
Labels: feature

#72 `readOnly` Keyword Has Been Removed from `AdminUserAuthServiceImpl` and `UserAuthServiceImpl` Services Because Services Have Insert/Update Transactions
  src/main/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
Labels: bug

#71 Improvement GitHub community standart
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  SECURITY.md
Labels: documentation

#73 `docker-compose` and `README.md` Files Have Been Refactored & MySQL Port Has Been Changed as `3307`
  README.md
  docker-compose.yml
  src/main/resources/application-development.yml
Labels: refactor

#81 README.md File Has Been Updated
  README.md
Labels: in review, refactor

#80 Improvement issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/custom-template.md
  .github/ISSUE_TEMPLATE/feature-request.md
  ISSUE_TEMPLATE.md
Labels: documentation, in review

#86 Fix Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, done

#74 Implementation of Update User Status Process
  src/main/java/com/ays/auth/model/AysIdentity.java
  src/main/java/com/ays/auth/model/enums/AysTokenClaims.java
  src/main/java/com/ays/user/controller/UserSelfController.java
  src/main/java/com/ays/user/model/User.java
  src/main/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequest.java
  src/main/java/com/ays/user/model/entity/UserEntity.java
  src/main/java/com/ays/user/model/enums/UserSupportStatus.java
  src/main/java/com/ays/user/model/mapper/UserSaveRequestToUserMapper.java
  src/main/java/com/ays/user/service/UserSelfService.java
  src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserSaveServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserSelfServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserServiceImpl.java
  src/main/resources/db/changelog/changes/1-ays-ddl.xml
  src/main/resources/db/changelog/changes/2-ays-dml.xml
  src/test/java/com/ays/user/controller/UserSelfControllerTest.java
  src/test/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequestBuilder.java
  src/test/java/com/ays/user/model/entity/UserEntityBuilder.java
  src/test/java/com/ays/user/service/impl/UserSelfServiceImplTest.java
Labels: feature, done

#83 Development Has Been Done to Enable Admins to Perform Operations Only Related to Their Own Users
  src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
  src/main/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImpl.java
  src/main/java/com/ays/admin_user/service/impl/AdminUserServiceImpl.java
  src/main/java/com/ays/auth/service/impl/AysTokenServiceImpl.java
  src/main/java/com/ays/auth/util/exception/UserIdNotValidException.java
  src/main/java/com/ays/auth/util/exception/UserNotActiveException.java
  src/main/java/com/ays/auth/util/exception/UserNotVerifiedException.java
  src/main/java/com/ays/common/model/AysSpecification.java
  src/main/java/com/ays/user/controller/UserController.java
  src/main/java/com/ays/user/repository/UserRepository.java
  src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
  src/main/java/com/ays/user/service/impl/UserServiceImpl.java
  src/main/resources/db/changelog/changes/2-ays-dml.xml
  src/test/java/com/ays/AbstractUnitTest.java
  src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
  src/test/java/com/ays/admin_user/service/impl/AdminUserServiceImplTest.java
  src/test/java/com/ays/auth/model/AysTokenBuilder.java
  src/test/java/com/ays/auth/model/dto/request/AysTokenRefreshRequestBuilder.java
  src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java
  src/test/java/com/ays/user/service/impl/UserServiceImplTest.java
Labels: feature, done
